import { Inter} from "next/font/google";
import "../globals.css";
import Footer from "@/app/(main)/components/Footer";
import Navbar from "@/app/(main)/components/Navbar";

const interFont = Inter({
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="light"
      lang="en"
      className={`${interFont.className} h-full antialiased bg-linear-to-b from-[#fff9f1] to-[#fff5ea]` }
    >
      <body className="min-h-full flex flex-col">
      <div className="container mx-auto">
        <Navbar />
        {children}
        <Footer />
      </div>
      </body>
    </html>
  );
}
